### ISSUE TITLE
Add Portugese translation

### ISSUE THREAD

**Issue by jstsch** [fightforthefuture/digital-climate-strike#89]
Hi! One of my customers (a large foundation) asked me today to enable the digital climate strike on their site. It's multilingual, where one of the main audiences is Brazil. However, PT is not available currently.

I've attached a yaml with the correct translations. Would be great if it can be added still, although I know the strike is only a few days from now.

```yaml
full_page:
  body: '
      <span class="dcs-website-name__default">Noso</span>
      <span class="dcs-website-name__prefix">O</span>
      <span class="dcs-website-name__website">site</span>
      <span class="dcs-website-name"></span>
      se juntou<br />
      hoje à<br />
      #GreveGlobalpeloClima.<br />
      E você?'
  ready:  'Estamos prontos. ➔'
  footer: 'Você poderá acessar nosso site amanhã, dia <time id="dcs-tomorrow-date" datetime="2019-09-21">21 de setembro</time>.'
footer:
  body: 'Nosso site se juntará à #GreveGlobalpeloClima no dia <time id="dcs-strike-date" datetime="2019-09-20">20 de setembro</time>. E você?'
  ready: 'Sim, eu também. ➔'

title: 'Digital Climate Strike'
logo_alt: 'Logo da Digital Climate Strike'
close_overlay: 'Fechar mensagem'
close_banner: 'Fechar banner'
```
